### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by blatinier** [blatinier/objectifzero#71]
- [x] Link to github
 - [x] See new european RGDB stuff and legal stuff to put there
 - [x] Credits for icons (cf below)
 - [x] Other ?
 - [x] Be careful about the display of it (for example on the Home page, the Footer doesn't have a layout around it)

**Comment by blatinier** [comment]
Icons credit: 
    <div>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>

**Comment by Far3t** [comment]
Be careful about the display of it (for example on the Home page, the Footer doesn't have a layout around it)

**Comment by blatinier** [comment]
No need for legal stuff since it's not a professional stuff
