### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by blatinier** [blatinier/objectifzero#78]
Find a logo (how about the Humming Bird?) and set it up.

**Comment by anaufalm** [comment]
You want a logo for this project?

Is it open source? I cant see your license files.

**Comment by blatinier** [comment]
It's open source, I'm adding the license files as I write you.
If you are up to contribute a logo that fits the project and allow me to use it under the AGPL I would be happy to have your contribution :)

**Comment by jackingpanda** [comment]
That's great, you can give us the brief so we can develop a logo for your project. E.g the type of logo you like, the color, etc.

**Comment by blatinier** [comment]
Just to set things straight, are you proposing to create a logo for free that will fall under the AGPL license of this project? I ask since I see you look like professional designers.

**Comment by anaufalm** [comment]
Yaa sure, this is for free. But you can add our name as contributor in redmi file or etc :)
